// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240629214848_add_ActionHistory")]
    partial class add_ActionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BaggageTagsSequence")
                .HasMax(999999L)
                .IsCyclic();

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("Core.FlightContext.BaseFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArrivalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DestinationFromId")
                        .HasColumnType("text");

                    b.Property<string>("DestinationToId")
                        .HasColumnType("text");

                    b.Property<string>("FlightType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationFromId");

                    b.HasIndex("DestinationToId");

                    b.ToTable("Flights", (string)null);

                    b.HasDiscriminator<string>("FlightType").HasValue("BaseFlight");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Property<string>("RegistrationCode")
                        .HasColumnType("text");

                    b.Property<string>("AircraftTypeId")
                        .HasColumnType("text");

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<int>("JumpSeatsAvailable")
                        .HasColumnType("integer");

                    b.Property<string>("SeatMapId")
                        .HasColumnType("text");

                    b.HasKey("RegistrationCode");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("CountryId");

                    b.HasIndex("SeatMapId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.AircraftType", b =>
                {
                    b.Property<string>("AircraftTypeIATACode")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.HasKey("AircraftTypeIATACode");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.Property<string>("CarrierCode")
                        .HasColumnType("text");

                    b.Property<int?>("AccountingCode")
                        .HasColumnType("integer");

                    b.Property<string>("AirlinePrefix")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarrierCode");

                    b.HasIndex("CountryId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.Property<string>("IATAAirportCode")
                        .HasColumnType("text");

                    b.Property<string>("AirportName")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.HasKey("IATAAirportCode");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaggageId")
                        .HasColumnType("uuid");

                    b.Property<string>("BaggageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlightId", "BaggageId");

                    b.HasIndex("BaggageId");

                    b.ToTable("FlightBaggage");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.HasKey("CommentId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightComment");
                });

            modelBuilder.Entity("Core.FlightContext.ScheduledFlight", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("Airline")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTimes")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("Codeshare")
                        .HasColumnType("text[]");

                    b.Property<string>("DepartureTimes")
                        .HasColumnType("jsonb");

                    b.Property<string>("DestinationFrom")
                        .HasColumnType("text");

                    b.Property<string>("DestinationTo")
                        .HasColumnType("text");

                    b.Property<string>("FlightDuration")
                        .HasColumnType("jsonb");

                    b.HasKey("FlightNumber");

                    b.ToTable("ScheduledFlights");
                });

            modelBuilder.Entity("Core.HistoryTracking.ActionHistory<object>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerOrItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerializedNewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("SerializedOldValue")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassengerOrItemId");

                    b.ToTable("ActionHistory");
                });

            modelBuilder.Entity("Core.PassengerContext.APIS.APISData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryOfIssueId")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateOfIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalityId")
                        .HasColumnType("text");

                    b.Property<Guid?>("PassengerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryOfIssueId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassengerId");

                    b.ToTable("APISData");
                });

            modelBuilder.Entity("Core.PassengerContext.APIS.Country", b =>
                {
                    b.Property<string>("Country2LetterCode")
                        .HasColumnType("text");

                    b.Property<string[]>("AircraftRegistrationPrefix")
                        .HasColumnType("text[]");

                    b.Property<string>("Country3LetterCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEEACountry")
                        .HasColumnType("boolean");

                    b.HasKey("Country2LetterCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Core.PassengerContext.BasePassengerOrItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PassengerOrItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailsId")
                        .IsUnique();

                    b.ToTable("Passengers", (string)null);

                    b.HasDiscriminator<string>("PassengerOrItemType").HasValue("BasePassengerOrItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Property<string>("PNR")
                        .HasColumnType("text");

                    b.Property<string>("FlightItinerary")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlightItinerary");

                    b.HasKey("PNR");

                    b.ToTable("BookingReferences");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PredefinedCommentId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("PredefinedCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardholderFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardholderLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MilesAvailable")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TierLever")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("FrequentFlyerCards");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.PassengerBookingDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssociatedPassengerBookingDetailsId")
                        .HasColumnType("uuid");

                    b.Property<int>("BaggageAllowance")
                        .HasColumnType("integer");

                    b.Property<string>("BookedClass")
                        .HasColumnType("jsonb")
                        .HasColumnName("BookedClass");

                    b.Property<string>("BookedSSR")
                        .HasColumnType("jsonb")
                        .HasColumnName("BookedSSR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequentFlyerCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PNRId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PassengerOrItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PriorityBoarding")
                        .HasColumnType("boolean");

                    b.Property<string>("ReservedSeats")
                        .HasColumnType("jsonb")
                        .HasColumnName("ReservedSeats");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedPassengerBookingDetailsId")
                        .IsUnique();

                    b.HasIndex("PNRId");

                    b.ToTable("PassengerBookingDetails");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.PredefinedComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PredefinedComments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SSRCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFreeTextMandatory")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.ToTable("SSRCodes");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.Property<Guid>("PassengerOrItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BoardingSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BoardingZone")
                        .HasColumnType("text");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NotTravellingReason")
                        .HasColumnType("integer");

                    b.HasKey("PassengerOrItemId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("PassengerFlight");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.SpecialServiceRequest", b =>
                {
                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.Property<string>("SSRCodeId")
                        .HasColumnType("text");

                    b.Property<string>("FreeText")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("PassengerId", "FlightId", "SSRCodeId");

                    b.HasIndex("FlightId");

                    b.HasIndex("SSRCodeId");

                    b.ToTable("SpecialServiceRequests");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PassengerOrItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerOrItemId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Core.SeatingContext.SeatMap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FlightClassesSpecification")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlightClassesSpecification");

                    b.HasKey("Id");

                    b.ToTable("SeatMaps");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.HasBaseType("Core.FlightContext.BaseFlight");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text");

                    b.Property<string>("BoardingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DividerPlacedBehindRow")
                        .HasColumnType("integer");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScheduledFlightId")
                        .HasColumnType("text");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ScheduledFlightId");

                    b.HasDiscriminator().HasValue("Scheduled");
                });

            modelBuilder.Entity("Core.FlightContext.OtherFlight", b =>
                {
                    b.HasBaseType("Core.FlightContext.BaseFlight");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("text")
                        .HasColumnName("OtherFlightFltNumber");

                    b.HasDiscriminator().HasValue("Other");
                });

            modelBuilder.Entity("Core.PassengerContext.CabinBaggageRequiringSeat", b =>
                {
                    b.HasBaseType("Core.PassengerContext.BasePassengerOrItem");

                    b.HasDiscriminator().HasValue("CBBG");
                });

            modelBuilder.Entity("Core.PassengerContext.ExtraSeat", b =>
                {
                    b.HasBaseType("Core.PassengerContext.BasePassengerOrItem");

                    b.HasDiscriminator().HasValue("EXST");
                });

            modelBuilder.Entity("Core.PassengerContext.Infant", b =>
                {
                    b.HasBaseType("Core.PassengerContext.BasePassengerOrItem");

                    b.Property<Guid>("AssociatedAdultPassengerId")
                        .HasColumnType("uuid");

                    b.HasIndex("AssociatedAdultPassengerId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Infant");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.HasBaseType("Core.PassengerContext.BasePassengerOrItem");

                    b.Property<int>("BaggageAllowance")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FrequentFlyerCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InfantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PriorityBoarding")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Passenger");
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "FinalDestination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("PassengerCheckedBags")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.BaggageContext.BaggageTag", "BaggageTag", b1 =>
                        {
                            b1.Property<Guid>("BaggageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TagNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TagNumber");

                            b1.Property<string>("TagType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TagType");

                            b1.HasKey("BaggageId");

                            b1.ToTable("Baggage");

                            b1.WithOwner()
                                .HasForeignKey("BaggageId");
                        });

                    b.OwnsOne("Core.BaggageContext.SpecialBag", "SpecialBag", b1 =>
                        {
                            b1.Property<Guid>("BaggageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SpecialBagDescription")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("SpecialBagDescription");

                            b1.Property<string>("SpecialBagType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SpecialBagType");

                            b1.HasKey("BaggageId");

                            b1.ToTable("Baggage");

                            b1.WithOwner()
                                .HasForeignKey("BaggageId");
                        });

                    b.Navigation("BaggageTag");

                    b.Navigation("FinalDestination");

                    b.Navigation("Passenger");

                    b.Navigation("SpecialBag");
                });

            modelBuilder.Entity("Core.FlightContext.BaseFlight", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "DestinationFrom")
                        .WithMany("Departures")
                        .HasForeignKey("DestinationFromId");

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "DestinationTo")
                        .WithMany("Arrivals")
                        .HasForeignKey("DestinationToId");

                    b.Navigation("Airline");

                    b.Navigation("DestinationFrom");

                    b.Navigation("DestinationTo");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.AircraftType", "AircraftType")
                        .WithMany()
                        .HasForeignKey("AircraftTypeId");

                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany("Fleet")
                        .HasForeignKey("AirlineId");

                    b.HasOne("Core.PassengerContext.APIS.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Core.SeatingContext.SeatMap", "SeatMap")
                        .WithMany()
                        .HasForeignKey("SeatMapId");

                    b.Navigation("AircraftType");

                    b.Navigation("Airline");

                    b.Navigation("Country");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.HasOne("Core.PassengerContext.APIS.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.HasOne("Core.PassengerContext.APIS.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.HasOne("Core.BaggageContext.Baggage", "Baggage")
                        .WithMany("Flights")
                        .HasForeignKey("BaggageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.BaseFlight", "Flight")
                        .WithMany("ListOfCheckedBaggage")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baggage");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightComment", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.Comment", "Comment")
                        .WithMany("LinkedToFlights")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("Comments")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.HistoryTracking.ActionHistory<object>", b =>
                {
                    b.HasOne("Core.PassengerContext.BasePassengerOrItem", "PassengerOrItem")
                        .WithMany("CustomerHistory")
                        .HasForeignKey("PassengerOrItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassengerOrItem");
                });

            modelBuilder.Entity("Core.PassengerContext.APIS.APISData", b =>
                {
                    b.HasOne("Core.PassengerContext.APIS.Country", "CountryOfIssue")
                        .WithMany()
                        .HasForeignKey("CountryOfIssueId");

                    b.HasOne("Core.PassengerContext.APIS.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("Core.PassengerContext.BasePassengerOrItem", "Passenger")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CountryOfIssue");

                    b.Navigation("Nationality");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.BasePassengerOrItem", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.PassengerBookingDetails", "BookingDetails")
                        .WithOne("PassengerOrItem")
                        .HasForeignKey("Core.PassengerContext.BasePassengerOrItem", "BookingDetailsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.HasOne("Core.PassengerContext.BasePassengerOrItem", "Passenger")
                        .WithMany("Comments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Booking.PredefinedComment", "PredefinedComment")
                        .WithMany()
                        .HasForeignKey("PredefinedCommentId");

                    b.Navigation("Passenger");

                    b.Navigation("PredefinedComment");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithOne("FrequentFlyerCard")
                        .HasForeignKey("Core.PassengerContext.Booking.FrequentFlyer", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.PassengerBookingDetails", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.PassengerBookingDetails", "AssociatedPassengerBookingDetails")
                        .WithOne()
                        .HasForeignKey("Core.PassengerContext.Booking.PassengerBookingDetails", "AssociatedPassengerBookingDetailsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.PassengerContext.Booking.BookingReference", "PNR")
                        .WithMany("LinkedPassengers")
                        .HasForeignKey("PNRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedPassengerBookingDetails");

                    b.Navigation("PNR");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.HasOne("Core.FlightContext.BaseFlight", "Flight")
                        .WithMany("ListOfBookedPassengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.BasePassengerOrItem", "PassengerOrItem")
                        .WithMany("Flights")
                        .HasForeignKey("PassengerOrItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("PassengerOrItem");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.SpecialServiceRequest", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("SSRList")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("SpecialServiceRequests")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Booking.SSRCode", "SSRCode")
                        .WithMany()
                        .HasForeignKey("SSRCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("SSRCode");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.BasePassengerOrItem", "PassengerOrItem")
                        .WithMany("AssignedSeats")
                        .HasForeignKey("PassengerOrItemId");

                    b.Navigation("Flight");

                    b.Navigation("PassengerOrItem");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId");

                    b.HasOne("Core.FlightContext.ScheduledFlight", "ScheduledFlight")
                        .WithMany()
                        .HasForeignKey("ScheduledFlightId");

                    b.Navigation("Aircraft");

                    b.Navigation("ScheduledFlight");
                });

            modelBuilder.Entity("Core.PassengerContext.Infant", b =>
                {
                    b.HasOne("Core.PassengerContext.Passenger", "AssociatedAdultPassenger")
                        .WithOne("Infant")
                        .HasForeignKey("Core.PassengerContext.Infant", "AssociatedAdultPassengerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("AssociatedAdultPassenger");
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.BaseFlight", b =>
                {
                    b.Navigation("ListOfBookedPassengers");

                    b.Navigation("ListOfCheckedBaggage");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.Navigation("Arrivals");

                    b.Navigation("Departures");
                });

            modelBuilder.Entity("Core.PassengerContext.BasePassengerOrItem", b =>
                {
                    b.Navigation("AssignedSeats");

                    b.Navigation("Comments");

                    b.Navigation("CustomerHistory");

                    b.Navigation("Flights");

                    b.Navigation("TravelDocuments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Navigation("LinkedPassengers");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.Navigation("LinkedToFlights");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.PassengerBookingDetails", b =>
                {
                    b.Navigation("PassengerOrItem");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SSRList");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.Navigation("FrequentFlyerCard");

                    b.Navigation("Infant");

                    b.Navigation("PassengerCheckedBags");

                    b.Navigation("SpecialServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
